# Generated by Django 4.2.5 on 2023-10-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_image_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="name",
            new_name="title",
        ),
    ]
