# Generated by Django 4.2.6 on 2023-10-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_rename_name_image_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="size",
            name="tier",
        ),
        migrations.AddField(
            model_name="tier",
            name="sizes",
            field=models.ManyToManyField(blank=True, to="myapp.size"),
        ),
    ]
