# Generated by Django 4.2.6 on 2023-10-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_tier_gen_exp_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tier",
            old_name="gen_exp_link",
            new_name="generate_expiring_link",
        ),
    ]
