# Generated by Django 4.2.6 on 2023-10-09 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_image_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpiringLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=50, unique=True)),
                ("expiration_timestamp", models.DateTimeField()),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.image"
                    ),
                ),
            ],
        ),
    ]
