# Generated by Django 4.2.6 on 2023-10-09 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_alter_expiringlink_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.tier",
            ),
        ),
    ]
