# Generated by Django 4.2.6 on 2023-10-11 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0013_image_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="tier",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="myapp.tier"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="tier",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="myapp.tier"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
