# Generated by Django 4.2.6 on 2023-10-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_alter_image_tier_alter_profile_tier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tier",
            name="sizes",
            field=models.ManyToManyField(to="myapp.size"),
        ),
    ]
